# README:
# only need database and database admin for local dev

services:
  ollama:
    image: ollama/ollama
    container_name: ollama-container
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_entrypoint.sh:/usr/local/bin/ollama_entrypoint.sh
    entrypoint: ["/usr/bin/bash", "/usr/local/bin/ollama_entrypoint.sh"]
  
